# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Text-Sentence-Alignment
version:      0.10
version_from: lib/Text/Sentence/Alignment.pm
installdirs:  site
requires:
    List::Util:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
