---
name: Text-Sentence-Alignment
version: 0.12
author:
  - 'Cheng-Lung Sung <clsung@cpan.org>'
abstract: Two Sentence Alignment
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  List::Util: 0
  Test::More: 0
provides:
  Text::Sentence::Alignment:
    file: lib/Text/Sentence/Alignment.pm
    version: 0.12
generated_by: Module::Build version 0.2807
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
